SSENSE/vue-carousel

play/index.js
src/Carousel.vue

New feature that adds new space padding. 
New param where we can add a value in pixels. This will add padding left and right to show other slides. 
:spacePadding='50'

New feature add spacePadding

---

docs/source/examples/index.md

Updated documentation examples to clarify the required props for `:perPage`.

chore(examples): updated examples

---

docs/source/api/index.md

February 14, 2017 'autoplayHoverPause' default value was changed to 'true' in commit 30e60cd. But the documentation wasn't updated.

docs: change 'autoplayHoverPause' default: true

---

docs/source/api/index.md
src/Carousel.vue
tests/client/components/__snapshots__/carousel.spec.js.snap
tests/client/components/__snapshots__/navigation.spec.js.snap
tests/client/components/__snapshots__/slide.spec.js.snap

After 0.6.7 update you've introduced carousel wrapper ref but also removed its class from Carousel.vue component which results in all slides showing at the same time without wrapper's 'overflow: hidden' css property. This solves the problem.

fix(wrapper): Return wrapper class to related block

---

src/Carousel.vue

This will solve the issue with #139 , Currently the component tries to remove the listener **after** it's destroyed, This change will remove the listeners **before** the component is destroyed.

Fixes #139

---

postcss.config.js
src/Carousel.vue

This uses postcss's autoprefixer (vue-loader already pipes through postcss) to enable vendor prefixes, as well as setting the vendor prefixes on the v-bind style. I needed this for IE10 support.
Related: https://github.com/SSENSE/vue-carousel/issues/98

Add vendor specific style prefixes (fixes IE10 support)

---

play/index.js
src/Carousel.vue

methods `getCarouselWidth` should get the width of `VueCarousel-inner`, since if we slide a page, we're supposed to translate the width of a single page, rather than the width of `VueCarousel-wrapper`.
And what's more, this helps us to meet the needs related in [#163](https://github.com/SSENSE/vue-carousel/issues/163) with some css tricks, which I have provided a demo in vue-play.

CarouselWidth should be the width of VueCarousel-inner

---

src/Carousel.vue
src/Slide.vue

Set `passive` option to `false` when listen `touch` events on document, because maybe we want to prevent default event like link with `<a>`. Chrome 56+ sets `passive` to `true` by default.

Fix passive event listener

---

README.md
src/Slide.vue

This is a documentation improve that get the fix line made by @JeanBarriere [here](https://github.com/SSENSE/vue-carousel/pull/185)
- Updated documentation to show how to use the event

Fix: Slide-click isTouch reference

---

src/Carousel.vue

Modern browsers are able to use native GPU acceleration, even without using translate3D.

Add IE11 support

---

src/Slide.vue

Changed use of array.includes(...) to array.indexOf(...) for IE compatibility
Has been tested in production on IE11.

Fixed bug in Slide.vue for IE Compatibility

---

play/index.js
src/Carousel.vue
src/mixins/autoplay.js
tests/client/components/__snapshots__/carousel.spec.js.snap
tests/client/components/carousel.spec.js

References #184.
By resetting the autoplay interval when `goToPage`  is being called, we can accomplish this functionality. Because hovering over the element will reset the autoplay interval, it should only be run when `autoplayHoverPause` is false.
I also added changes to the properties passed to the *Autoplay* example in the vue-play demos. Because `autoplayHoverPause` has a default value of `true`, it rendered the component with the same properties as in *Autoplay, pause on hover*.

Feature: Reset autoplay timeout on manual slide switch

---

src/Carousel.vue
tests/client/components/carousel.spec.js

I am not sure which issue I solved, but I think this one https://github.com/SSENSE/vue-carousel/issues/178
Steps to reproduce:
1. Configuration: `{ scrollPerPage: true, perPage: 2}`
2. Number of slides is 5
3. Click on first dot, if we are not on the first page
4. Click on second dot
Expected: Activating of second dot
Actual: Third dot is activated. Also, we cannot see 5th slide on carousel.

Bug fix: Wrong max offset calculations

---

src/Carousel.vue
src/Pagination.vue

Ref to issue #220 
I also face wrong `maxOffset` caused `navigateTo` broken in ver 0.81, but I found another PR #221 solved the offset problem

bug(carousel): fix navigateTo is not working as expected

---

src/Carousel.vue

Add a factor number to the space padding multiplication, to handle how the last slide is rendered.
Currently, the `last slide` is cropped by the `inner` div and is not fully visible.
By specifying `spacePaddingMaxOffsetFactor` to 0, 1 or 2, you can tweak how is rendered the last slide.
By setting to 0, the slide is positionned to the center.
By setting to 1, the slide is aligned to the right.
And by setting to 2 (the current behavior), we have the overflow case (see the screenshot).

Add space padding factor number to manage the last slide

---

src/Carousel.vue

Hi,
When the carousel is loaded, I want to navigate to a certain page number.
I can change the "navigateTo", but only when the carousel is loaded. And I don't know when the carousel is actually loaded (I'm using SSR)
With this emit, a parent component can know if the Carousel is done loading

Emit when carousel is mounted

---

src/Carousel.vue

The previous solution didn't work when manually switching slides using touch. Called restartAutoplay from the function onEnd. Tested on Vue-play. If you think there's a better place to call restartAutoplay lemme know. @quinnlangille

Improvement: #184

---

docs/source/api/index.md
src/Carousel.vue

Allow custom components to be used for rendering pagination and navigation, with access to the `carousel` provider.
The following named slots have been added:
1. `pagination`
2. `navigation`
```html
<carousel>
<slide>content</slide>
<custom-pagination slot="pagination" />
<custom-navigation slot="navigation" />
</carousel>
```
The pagination and navigation included in `vue-carousel` is somewhat limited. Adding named slots to allow custom components to be used to render these elements adds more flexibility without impacting the default usage. Without slots, its not possible for custom components to access the `carousel` provider.
To allow for more custom rendering of navigation and pagination elements.
Using vue-play in the browser. This is a very simple change, it should not impact the …

feat(render): Add slots to allow custom navigation and pagination

---

README.md

Added the missing properties to the repo's `README.md`.
3 properties were missing from the `README.md` file but were available on the official [API docs](https://ssense.github.io/vue-carousel/api/).  
Mentioned in #196.

docs(readme): updated README configuration section

---

README.md

The README says `autoHoverPause`'s default is `false`, but it's actually `true`. 
Changed the default val for the attr to the correct val.
Acurrate readme.. 
n/a

Fix fake news in readme

---

src/Carousel.vue
src/Pagination.vue
tests/client/components/__snapshots__/carousel.spec.js.snap

Updated the page count calculation for the carousel and pagination to properly display the correct number of pagination dots for scrollPerPage false
The current functionality is broken and very apparent when using scrollPerPage in vue play
I have only tested the implementation in vue play

Add correct calculation for pageCount when using scrollPerPage false

---

package.json
tests/client/components/carousel.spec.js
tests/client/components/navigation.spec.js
tests/client/components/slide.spec.js
yarn.lock

1. Added `vue-test-utils` to package.json
2. Rewritten all tests to use `vue-test-utils` retaining the original method used in each of the tests.
I have noticed some tests aren't doing anything while other does not generate exact same snapshot but those fixes will come later.
Effort being placed in so that work on increasing code coverage can eventually be carried out for the project.
1. All the assertion have been negated i.e. adding `.not` or removing `.not` to test if they can fail
2. `precommit` passed as before
N/A

Use vue-test-utils for testing

---

src/Carousel.vue

It is not possible to reach the last slide by using swipe when navigation is enabled
Before 0.16.0, it was not possible to reach the last slide by using navigation "next" button. Swiping everything worked fine. After update to 0.16.0, this behavor is inverted, i.e., I can reach the last slider by pressing "next" button but not by swiping. 
This Pull Request fixes a calculation issue that was creating this unexpected behavior.
Fixes issue https://github.com/SSENSE/vue-carousel/issues/345
There is already a Vue Play case for this in the project, and was also tested manually in all VuePlay cases

fix(carousel): calculation lastFullPageOffset
